# backend/openapi.yaml
swagger: '2.0' # OpenAPI 2.0 is commonly used for GCP API Gateway x-google-backend
info:
  title: Real Estate Knowledge Base API
  description: API for querying the real estate knowledge base LLM and related services.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /query:
    post:
      summary: Submit a query to the LLM
      description: Sends a user query to the backend LLM via the Cloud Function.
      operationId: submitLlmQuery
      x-google-backend:
        # Address is the invocation URL of the deployed Cloud Function
        address: https://us-east1-hio-gcp-kb.cloudfunctions.net/llm-query
        # deadline: 60 # Optional: Set a deadline in seconds (e.g., 60) if needed
      parameters:
        - in: body
          name: queryPayload
          description: JSON payload containing the user query
          required: true
          schema:
            type: object
            required:
              - query
            properties:
              query:
                type: string
                description: The natural language query for the knowledge base.
                example: "What are the zoning laws for properties near downtown?"
      responses:
        '200':
          description: Successful response from the LLM
          schema:
            type: object
            properties:
              response:
                type: string
                description: The answer generated by the LLM.
              sources:
                type: array
                items:
                  type: string
                description: List of potential source documents or references.
        '400':
          description: Bad Request - Invalid input payload
        '500':
          description: Internal Server Error - Backend function failed 